# Generated by Django 4.0.6 on 2022-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_color_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=100),
        ),
    ]
